### ISSUE TITLE
pip eazy_install not working-HTTP 403 error

### ISSUE THREAD

**Issue by izaakdehullu** [vovimayhem/vagrant-guest_ansible#18]
When I run the plugin I get the following error trace: 

............
Downloading http://pypi.python.org/packages/2.7/s/setuptools/setuptools-0.6c11-py2.7.egg
Traceback (most recent call last):
  File "ez_setup.py", line 278, in <module>
    main(sys.argv[1:])
  File "ez_setup.py", line 210, in main
    egg = download_setuptools(version, delay=0)
  File "ez_setup.py", line 158, in download_setuptools
    src = urllib2.urlopen(url)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: SSL is required

On the internet I read this has something to do with the fact PiPy has disabled HTTP access. See: 
https://github.com/zopefoundation/grokproject/issues/10

I was hoping I could just replace the http with https but the scripts are created dynamically so I stopped looking. Although the ez_setup.py is only 'used' in the in plugin code perhaps there is a fix?

**Comment by plopezmartin** [comment]
I worked around this by editing DEFAULT_URL in /path-to/site-packages/ez_setup.py and in /path-to/site-packages/distributed_setup.py to point to https from http.

**Comment by slicedevca** [comment]
There are pull requests that fix this, can we get them merged and another release?

**Comment by slicedevca** [comment]
This is resolved with PR #17
